spring.application.name=netak

spring.datasource.url=jdbc:postgresql://postgres:5432/netakapp
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=obeELK7uFk2UspcMH4tm0WDyByUp3EafFcHRw+ux76E=
jwt.token.access.life=1800
jwt.token.refresh.life=86400